default_install_hook_types:
  - pre-commit
repos:
  - repo: local
    hooks:
      - id: pre-commit-autoupdate
        name: Run pre-commit autoupdate
        entry: pre-commit autoupdate
        language: system
        pass_filenames: false
        # files: .pre-commit-config.yaml

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-symlinks
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: package-lock.json
      - id: check-json
        exclude: "package-lock.json|.vscode/.*"
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--no-sort-keys"
        exclude: "package-lock.json|.vscode/.*"
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: check-executables-have-shebangs
      - id: check-vcs-permalinks

  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
        exclude: package-lock.json

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks
        args:
          - --config
          - ".github/linters/.gitleaks.toml"

  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.24
    hooks:
      - id: actionlint
        args:
          - "-ignore"
          - "SC2086"
