# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
---
name: Get Repositories
description: 🗄️ Get organization or user repos based on the topics filter (with logic AND/OR) to use in the matrix job or another action.
author: Dariusz Porowski
branding:
  icon: list # https://feathericons.com
  color: gray-dark

inputs:
  owner:
    description: GitHub Organization or User name, default to `github.repository_owner`
    required: false
    default: ${{ github.repository_owner }}
  topics:
    description: Comma-separated list of repository topics
    required: false
  operator:
    description: Operator to use when filtering repositories by topics, `OR` or `AND`, default to `OR`
    required: false
    default: OR
  matrix-use:
    description: Output to use in the matrix job?, `true` or `false`
    required: false
    default: "true"
  format:
    description: Output format, `json` or `flat`, default to `json`
    required: false
    default: json
  delimiter:
    description: Delimiter to use when `format` is `flat`, default to `\n`
    required: false
  github-token:
    description: GitHub Token with `repo` scope, default to `github.token`
    required: false
    default: ${{ github.token }}

outputs:
  count:
    description: Number of found repositories
    value: ${{ steps.repos.outputs.count }}
  repos:
    description: Repositories
    value: ${{ steps.repos.outputs.repos }}
  format:
    description: Output format
    value: ${{ steps.repos.outputs.format }}

runs:
  using: composite
  steps:
    - name: Get Repositories
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      id: repos
      with:
        github-token: ${{ inputs.github-token || env.GITHUB_TOKEN }}
        script: |
          const path = require('path')
          const actionPath = path.join(process.env.GITHUB_ACTION_PATH, 'index.cjs')
          const script = require(actionPath)
          await script({ context, github, core })
      env:
        INPUT_OWNER: ${{ inputs.owner }}
        INPUT_TOPICS: ${{ inputs.topics }}
        INPUT_OPERATOR: ${{ inputs.operator }}
        INPUT_MATRIX_USE: ${{ inputs.matrix-use }}
        INPUT_FORMAT: ${{ inputs.format }}
        INPUT_DELIMITER: ${{ inputs.delimiter }}
