---
name: Draft Release

on:
  push:
    branches:
      - main

jobs:
  draft-release:
    name: Draft Release
    uses: raven-actions/.workflows/.github/workflows/__release-draft.yml@main
    secrets: inherit
