---
name: Publish Release

on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      tag-name:
        description: Tag name that the major tag will point to
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.tag-name || github.event.release.tag_name }}

jobs:
  gh-release-update:
    name: GitHub Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub App Token
        uses: wow-actions/use-app-token@v2
        id: get-token
        with:
          app_id: ${{ secrets.ORG_BOT_APP_ID }}
          private_key: ${{ secrets.ORG_BOT_PRIVATE_KEY }}
          fallback: ${{ github.token }}

      - name: Update release to the latest
        id: gh-release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          token: ${{ steps.get-token.outputs.BOT_TOKEN }}

      - name: Update the major tag to include the ${{ env.TAG_NAME }} changes
        id: update-major-tag
        uses: actions/publish-action@v0.2.2
        with:
          source-tag: ${{ env.TAG_NAME }}
          token: ${{ steps.get-token.outputs.BOT_TOKEN }}
